import type { Metadata } from "next";
import { Nanum_Gothic } from "next/font/google";
import "./globals.css";
import Head from "./head";
import Link from "next/link";

const inter = Nanum_Gothic({
  weight: ["400", "800"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const header = (
    <Link href="/">
      <h1 className="text-xl text-blue-600 underline underline-offset-4">
        프레쉬팟푸리
      </h1>
    </Link>
  );

  const footer = (
    <footer>
      <div>
        <h3>Developed by Charli</h3>
      </div>
    </footer>
  );
  return (
    <html lang="en">
      <Head />
      <body className={`${inter.className} bg-slate-300`}>
        <div className="container p-10 leading-loose mx-auto max-w-7xl bg-slate-100">
          {header}
          {children}
          {footer}
        </div>
      </body>
    </html>
  );
}
